### ISSUE TITLE
No Data Found on Players

### ISSUE THREAD

**Issue by wumbly12** [NathanCollaert/LiteDeathBan#2]
Hey again,
I ended up switching my little server over to spigot so we could use this plugin. This time the error I'm getting when I do some of the commands is "(name) has no data on this server." 

I checked the userdata folder and saw that I had a yml file containing my accounts information. I've tinkered around with things and can't seem to fix it.

**Comment by NathanCollaert** [comment]
Hey there,
Sorry for this inconvenience, the plugin was indeed checking for the player name instead of the player UUID in the commands resulting in them not working.
Thank you for reporting this bug, this is now fixed in the latest LDB version (1.1.1)!

**Comment by Zatiejo** [comment]
Hey! I don't mean to reply to an old closed Issue discussion...
However, I'm still having this issue.

There are no error logs. I'm using the latest version (3.3.7) and I'm not sure what's causing this. Latest version of PaperMC.

Is there something I need to change in the config? Is it because they're in spectator mode?
Currently it's unknown to me, and I'm really curious as to how to fix this.

I tried to use both the username (not displayname, username) and the UUID, just incase I needed to do it manually.

If you need, I'm willing to make a new opened discussion for this.
![2022-11-14_19 24 00](https://user-images.githubusercontent.com/61992533/201796034-863011f4-14df-4622-b58d-252d78c016bc.png)
